version: 0.0
os: linux

files:
  - source: /index.html
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: scripts/httpd_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/httpd_start.sh
      timeout: 300
      runas: root
branch_config:
  main:
    deploymentGroupName: web-dpg
    deploymentGroupConfig: 
      serviceRoleArn: arn:aws:iam::741448956481:role/codedeploy
